DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'UserRole') THEN
    CREATE TYPE "UserRole" AS ENUM ('ADMIN','LAWYER','BASIC','UNASSIGNED');
  END IF;
END $$;

ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User"
  ALTER COLUMN "role" TYPE "UserRole"
  USING (CASE
    WHEN "role" IN ('ADMIN','LAWYER','BASIC','UNASSIGNED') THEN "role"::"UserRole"
    ELSE 'UNASSIGNED'::"UserRole"
  END);

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'UNASSIGNED';
